### PR TITLE
Ignore static properties

### LINKED ISSUE #10: `ByIgnoringProperties<T>` causes static properties to be included
`ByIgnoringProperties<T>` causes static properties to be included when an object is logged with the destructuring operator.

In the example below, the static property `NotExpectedToBeIncluded` is unexpectedly written to the log.

```
using Destructurama;
using Serilog;

Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .WriteTo.Console()
    .Destructure.ByIgnoringProperties<TestType>(x => x.Ignore)
    .CreateLogger();

Log.Debug("{@Test}", new TestType());

// Result:
// {"Include": "Include", "NotExpectedToBeIncluded": "NotExpectedToBeIncluded", "$type": "TestType"}

public class TestType
{
    public string Include => "Include";
    public string Ignore => "Ignore";
    public static string NotExpectedToBeIncluded => "NotExpectedToBeIncluded";
}
```

NuGet package versions:
```
<PackageReference Include="Serilog.Sinks.Console" Version="4.0.0" />
<PackageReference Include="Destructurama.ByIgnoring" Version="1.1.0" />
```
[DestructuramaByIgnoringConsoleApp.zip](https://github.com/destructurama/by-ignoring/files/7446219/DestructuramaByIgnoringConsoleApp.zip)

### PR DESCRIPTION
**Pull request by sungam3r**
fixes #10

### CODE REVIEW

File: src/Destructurama.ByIgnoring/ByIgnoring/DestructureByIgnoringPolicy.cs [hunk 1]
```diff
@@ -35,7 +35,9 @@ public DestructureByIgnoringPolicy(params Expression<Func<TDestructure, object>>
             var runtimeProperties = _destructureType.GetRuntimeProperties();
 
             _propertiesToInclude = runtimeProperties
-                .Where(p=> p.CanRead)
+                .Where(p => p.CanRead)
+                .Where(p => !p.GetMethod.IsStatic)
+                .Where(p => p.GetIndexParameters().Length == 0)
```
Comment (sungam3r) [inline src/Destructurama.ByIgnoring/ByIgnoring/DestructureByIgnoringPolicy.cs:40]: > System.Reflection.TargetParameterCountException: 'Parameter count mismatch.'
> System.InvalidCastException: 'Unable to cast object of type 'Serilog.Events.ScalarValue' to type 'Serilog.Events.StructureValue'.'

was before this change inside `PropertyNamesInExpressionsAreIgnoredWhenDestructuring`

**Comment by nblumhardt** [comment]
Awesome 👍
